import React from "react";
import { useCurrentFrame, interpolate, spring, useVideoConfig } from "remotion";
import { colors } from "../styles";
import { DashboardLayout, AnimatedCursor, TypewriterText, type CursorKeyframe } from "../helpers";

const queueItems = [
  { name: "Bank Reconciliation", detail: "847 matches · 3 exceptions", approveFrame: 140 },
  { name: "Monthly P&L Report", detail: "Generated by Reports agent", approveFrame: 200 },
  { name: "Accrual Entries", detail: "12 items · $84,300 total", approveFrame: 250 },
];

const exceptions = [
  { num: 1, date: "Apr 3", desc: "Wire transfer #4421", amount: "$1,200", issue: "Timing difference" },
  { num: 2, date: "Apr 5", desc: "Vendor payment #889", amount: "$840", issue: "Missing invoice" },
  { num: 3, date: "Apr 7", desc: "Refund #1102", amount: "$300", issue: "Duplicate entry" },
];

const cursorKeyframes: CursorKeyframe[] = [
  { x: 800, y: 300, frame: 20 },               // Start on detail panel
  { x: 850, y: 350, frame: 50 },               // Move over exception row 1
  { x: 850, y: 385, frame: 70 },               // Move over exception row 2
  { x: 850, y: 420, frame: 85 },               // Move over exception row 3
  { x: 1050, y: 520, frame: 115 },             // Move to Approve button
  { x: 1050, y: 520, frame: 130, click: true }, // Click Approve!
  // Item 1 approved, switch to item 2
  { x: 250, y: 260, frame: 160 },               // Move to queue item 2
  { x: 250, y: 260, frame: 165, click: true },  // Click to select
  { x: 1050, y: 520, frame: 185 },              // Move to Approve
  { x: 1050, y: 520, frame: 195, click: true }, // Click Approve!
  // Item 2 approved, switch to item 3
  { x: 250, y: 310, frame: 215 },               // Move to queue item 3
  { x: 250, y: 310, frame: 220, click: true },  // Click to select
  { x: 1050, y: 520, frame: 235 },              // Move to Approve
  { x: 1050, y: 520, frame: 245, click: true }, // Click Approve!
  { x: 700, y: 400, frame: 270 },               // Settle
];

export const ApproveScene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const sceneOpacity = Math.min(
    interpolate(frame, [0, 15], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
    interpolate(frame, [270, 300], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })
  );

  // Which item is selected (0, 1, or 2)
  const selectedItem = frame < 160 ? 0 : frame < 215 ? 1 : 2;

  // Which items are approved
  const approvedItems = queueItems.map((item) => frame >= item.approveFrame + 5);

  // Approve button flash
  const getApproveFlash = (approveFrame: number) => {
    if (frame >= approveFrame && frame < approveFrame + 12) {
      return interpolate(frame, [approveFrame, approveFrame + 12], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
    }
    return 0;
  };

  const currentFlash = getApproveFlash(queueItems[selectedItem].approveFrame);

  return (
    <div style={{ opacity: sceneOpacity }}>
      <DashboardLayout activeIndex={3} breadcrumb="Close Management › April 2026 › Review Queue">
        <div style={{ padding: "20px 28px", height: "100%", display: "flex", gap: 20 }}>
          {/* Left panel — Queue */}
          <div style={{ width: "32%", display: "flex", flexDirection: "column" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
              <span style={{ fontSize: 16, fontWeight: 600, color: colors.textPrimary }}>Review Queue</span>
              <span style={{ fontSize: 12, color: colors.textMuted }}>
                {approvedItems.filter(Boolean).length} of 3 reviewed
              </span>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {queueItems.map((item, i) => {
                const isSelected = i === selectedItem;
                const isApproved = approvedItems[i];
                const rowDelay = 5 + i * 8;
                const rowOpacity = interpolate(frame, [rowDelay, rowDelay + 12], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

                return (
                  <div key={item.name} style={{
                    opacity: rowOpacity,
                    padding: "14px 16px",
                    borderRadius: 10,
                    border: `1px solid ${isSelected ? colors.highlight : colors.border}`,
                    backgroundColor: isSelected ? "rgba(166, 124, 82, 0.06)" : "rgba(255,255,255,0.02)",
                  }}>
                    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                      <span style={{ fontSize: 13, fontWeight: 500, color: colors.textPrimary }}>{item.name}</span>
                      {isApproved ? (
                        <span style={{ fontSize: 11, color: colors.success, fontWeight: 500 }}>✓ Approved</span>
                      ) : (
                        <span style={{ fontSize: 11, color: colors.textMuted }}>⏳ Pending</span>
                      )}
                    </div>
                    <span style={{ fontSize: 11, color: colors.textMuted, marginTop: 4, display: "block" }}>
                      {item.detail}
                    </span>
                  </div>
                );
              })}
            </div>

            {/* Queue status */}
            {approvedItems.every(Boolean) && (
              <div style={{
                marginTop: 16, padding: "10px 14px", borderRadius: 8,
                backgroundColor: colors.successLight,
                display: "flex", alignItems: "center", gap: 8,
                opacity: spring({ frame: frame - 255, fps, config: { damping: 20, stiffness: 100, mass: 0.5 } }),
              }}>
                <div style={{ width: 7, height: 7, borderRadius: "50%", backgroundColor: colors.success }} />
                <span style={{ fontSize: 12, color: colors.success, fontWeight: 500 }}>All items reviewed</span>
              </div>
            )}
          </div>

          {/* Right panel — Detail view */}
          <div style={{ flex: 1, borderRadius: 10, border: `1px solid ${colors.border}`, backgroundColor: "rgba(255,255,255,0.01)", padding: 24, display: "flex", flexDirection: "column" }}>
            {/* Detail header */}
            <div style={{ marginBottom: 20 }}>
              <span style={{ fontSize: 18, fontWeight: 600, color: colors.textPrimary }}>
                {queueItems[selectedItem].name}
              </span>
              <span style={{ fontSize: 12, color: colors.textMuted, marginLeft: 12 }}>— April 2026</span>
            </div>

            {/* Summary stats */}
            <div style={{ display: "flex", gap: 24, marginBottom: 20 }}>
              <div>
                <span style={{ fontSize: 11, color: colors.textMuted, display: "block" }}>Agent</span>
                <span style={{ fontSize: 13, color: colors.highlight, fontWeight: 500 }}>
                  {selectedItem === 0 ? "Reconciliations" : selectedItem === 1 ? "Reports" : "Reconciliations"}
                </span>
              </div>
              <div>
                <span style={{ fontSize: 11, color: colors.textMuted, display: "block" }}>Completed</span>
                <span style={{ fontSize: 13, color: colors.textPrimary }}>10:42 AM</span>
              </div>
              {selectedItem === 0 && (
                <>
                  <div>
                    <span style={{ fontSize: 11, color: colors.textMuted, display: "block" }}>Matched</span>
                    <span style={{ fontSize: 13, color: colors.success, fontWeight: 500 }}>847 / 850 (99.6%)</span>
                  </div>
                  <div>
                    <span style={{ fontSize: 11, color: colors.textMuted, display: "block" }}>Exceptions</span>
                    <span style={{ fontSize: 13, color: colors.warning, fontWeight: 500 }}>3 items ($2,340)</span>
                  </div>
                </>
              )}
            </div>

            {/* Exception table (for Bank Reconciliation) */}
            {selectedItem === 0 && (
              <div style={{ borderRadius: 8, border: `1px solid ${colors.border}`, overflow: "hidden", marginBottom: 20 }}>
                <div style={{
                  display: "flex", backgroundColor: "rgba(255,255,255,0.02)",
                  borderBottom: `1px solid ${colors.border}`, padding: "8px 14px",
                }}>
                  {["#", "Date", "Description", "Amount", "Issue"].map((col, i) => (
                    <div key={col} style={{
                      width: ["6%", "14%", "34%", "18%", "28%"][i],
                      fontSize: 10, fontWeight: 500, color: colors.textMuted, textTransform: "uppercase", letterSpacing: "0.05em",
                    }}>
                      {col}
                    </div>
                  ))}
                </div>
                {exceptions.map((exc) => (
                  <div key={exc.num} style={{
                    display: "flex", padding: "10px 14px",
                    borderBottom: `1px solid ${colors.border}`,
                  }}>
                    <div style={{ width: "6%", fontSize: 12, color: colors.textMuted }}>{exc.num}</div>
                    <div style={{ width: "14%", fontSize: 12, color: colors.textMuted }}>{exc.date}</div>
                    <div style={{ width: "34%", fontSize: 12, color: colors.textPrimary }}>{exc.desc}</div>
                    <div style={{ width: "18%", fontSize: 12, color: colors.warning, fontFamily: "monospace" }}>{exc.amount}</div>
                    <div style={{ width: "28%", fontSize: 12, color: colors.textMuted }}>{exc.issue}</div>
                  </div>
                ))}
              </div>
            )}

            {/* P&L summary (for Monthly P&L) */}
            {selectedItem === 1 && (
              <div style={{ padding: 16, borderRadius: 8, border: `1px solid ${colors.border}`, marginBottom: 20 }}>
                <span style={{ fontSize: 13, color: colors.textPrimary, fontWeight: 500, display: "block", marginBottom: 8 }}>Report Summary</span>
                <div style={{ display: "flex", gap: 32 }}>
                  <div><span style={{ fontSize: 11, color: colors.textMuted }}>Revenue</span><br /><span style={{ fontSize: 14, color: colors.success, fontFamily: "monospace" }}>$1,247,500</span></div>
                  <div><span style={{ fontSize: 11, color: colors.textMuted }}>Expenses</span><br /><span style={{ fontSize: 14, color: colors.warning, fontFamily: "monospace" }}>$892,300</span></div>
                  <div><span style={{ fontSize: 11, color: colors.textMuted }}>Net Income</span><br /><span style={{ fontSize: 14, color: colors.textPrimary, fontWeight: 600, fontFamily: "monospace" }}>$355,200</span></div>
                </div>
              </div>
            )}

            {/* Accrual summary */}
            {selectedItem === 2 && (
              <div style={{ padding: 16, borderRadius: 8, border: `1px solid ${colors.border}`, marginBottom: 20 }}>
                <span style={{ fontSize: 13, color: colors.textPrimary, fontWeight: 500, display: "block", marginBottom: 8 }}>Accrual Summary</span>
                <div style={{ display: "flex", gap: 32 }}>
                  <div><span style={{ fontSize: 11, color: colors.textMuted }}>Items</span><br /><span style={{ fontSize: 14, color: colors.textPrimary, fontFamily: "monospace" }}>12</span></div>
                  <div><span style={{ fontSize: 11, color: colors.textMuted }}>Total</span><br /><span style={{ fontSize: 14, color: colors.textPrimary, fontFamily: "monospace" }}>$84,300</span></div>
                  <div><span style={{ fontSize: 11, color: colors.textMuted }}>Variance</span><br /><span style={{ fontSize: 14, color: colors.success, fontFamily: "monospace" }}>$0</span></div>
                </div>
              </div>
            )}

            {/* Spacer */}
            <div style={{ flex: 1 }} />

            {/* Audit trail */}
            <div style={{ borderTop: `1px solid ${colors.border}`, paddingTop: 14, marginBottom: 14 }}>
              <span style={{ fontSize: 11, fontWeight: 500, color: colors.textMuted, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 8, display: "block" }}>
                Audit Trail
              </span>
              <div style={{ fontSize: 12, color: colors.textMuted, lineHeight: 1.8 }}>
                <div>10:42 — Agent completed reconciliation</div>
                {approvedItems[selectedItem] && (
                  <>
                    <div style={{ color: colors.textSecondary }}>
                      <TypewriterText text="10:45 — Reviewed by S. Kim" startFrame={queueItems[selectedItem].approveFrame + 5} charsPerFrame={1.2} style={{ color: colors.textSecondary }} />
                    </div>
                    <div style={{ color: colors.success }}>
                      <TypewriterText text="10:45 — Approved ✓" startFrame={queueItems[selectedItem].approveFrame + 25} charsPerFrame={1.2} style={{ color: colors.success }} />
                    </div>
                  </>
                )}
              </div>
            </div>

            {/* Approve button */}
            {!approvedItems[selectedItem] && (
              <div style={{ display: "flex", gap: 10 }}>
                <div style={{
                  padding: "10px 24px", borderRadius: 8,
                  backgroundColor: currentFlash > 0
                    ? `rgba(90, 122, 100, ${0.3 + currentFlash * 0.7})`
                    : colors.success,
                  color: "white", fontSize: 13, fontWeight: 500,
                  boxShadow: currentFlash > 0 ? `0 0 20px rgba(90, 122, 100, ${currentFlash * 0.5})` : "none",
                }}>
                  ✓ Approve
                </div>
                <div style={{
                  padding: "10px 24px", borderRadius: 8,
                  border: `1px solid ${colors.border}`,
                  color: colors.textSecondary, fontSize: 13, fontWeight: 500,
                }}>
                  Request Changes
                </div>
              </div>
            )}

            {approvedItems[selectedItem] && (
              <div style={{
                padding: "10px 24px", borderRadius: 8, width: "fit-content",
                backgroundColor: colors.successLight, color: colors.success, fontSize: 13, fontWeight: 500,
              }}>
                ✓ Approved
              </div>
            )}
          </div>
        </div>

        <AnimatedCursor keyframes={cursorKeyframes} />
      </DashboardLayout>
    </div>
  );
};
