/**
 * Vergo Excel Template Generator
 * Run with: npm run generate-templates
 *
 * Generates styled .xlsx files in /public/downloads/ for all templates.
 * Custom generators for high-traffic templates; generic fallback for the rest.
 */

import ExcelJS from "exceljs";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

// ── Resolve paths ──────────────────────────────────────────────────────────
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");
const OUTPUT_DIR = join(ROOT, "public", "downloads");

// ── Import template data ───────────────────────────────────────────────────
const { templates } = await import("../src/data/templates.js");

// ── Vergo brand colours ────────────────────────────────────────────────────
const BRAND = {
  headerBg: "1A1A2E",       // Dark navy
  headerFg: "FFFFFF",       // White text
  accentBg: "EEF2FF",       // Light indigo tint
  accentFg: "4F46E5",       // Indigo text
  rowAlt: "F9FAFB",         // Alternating row
  border: "E5E7EB",         // Border grey
  green: "16A34A",          // Success green
  red: "DC2626",            // Error red
  darkText: "111111",
  mutedText: "6B7280",
};

// ── Shared helpers ─────────────────────────────────────────────────────────
function headerStyle(bold = true): Partial<ExcelJS.Style> {
  return {
    font: { bold, color: { argb: `FF${BRAND.headerFg}` }, size: 11 },
    fill: {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: `FF${BRAND.headerBg}` },
    },
    alignment: { vertical: "middle", horizontal: "center", wrapText: true },
    border: {
      bottom: { style: "thin", color: { argb: `FF${BRAND.border}` } },
    },
  };
}

function dataStyle(rowIndex: number, center = false): Partial<ExcelJS.Style> {
  const bg = rowIndex % 2 === 0 ? "FFFFFFFF" : `FF${BRAND.rowAlt}`;
  return {
    fill: { type: "pattern", pattern: "solid", fgColor: { argb: bg } },
    alignment: { vertical: "middle", horizontal: center ? "center" : "left", wrapText: true },
    border: {
      bottom: { style: "hair", color: { argb: `FF${BRAND.border}` } },
    },
    font: { color: { argb: `FF${BRAND.darkText}` }, size: 10 },
  };
}

function currencyStyle(rowIndex: number): Partial<ExcelJS.Style> {
  return {
    ...dataStyle(rowIndex),
    numFmt: '"$"#,##0.00',
    alignment: { horizontal: "right", vertical: "middle" },
  };
}

function addBrandingFooter(sheet: ExcelJS.Worksheet, startRow: number) {
  const row = sheet.getRow(startRow + 2);
  const cell = row.getCell(1);
  cell.value = "Generated by Vergo · tryvergo.com · Free accounting templates";
  cell.font = { italic: true, color: { argb: `FF${BRAND.mutedText}` }, size: 9 };
  cell.alignment = { horizontal: "left" };
}

function setColWidths(sheet: ExcelJS.Worksheet, widths: number[]) {
  widths.forEach((w, i) => {
    sheet.getColumn(i + 1).width = w;
  });
}

function freezeHeader(sheet: ExcelJS.Worksheet) {
  sheet.views = [{ state: "frozen", ySplit: 1, xSplit: 0 }];
}

// ── Custom generators ──────────────────────────────────────────────────────

function buildMonthEndCloseChecklist(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("Month-End Close Checklist");
  setColWidths(ws, [42, 22, 14, 18, 32]);
  freezeHeader(ws);

  // Header
  const headers = ["Task", "Owner", "Due Date", "Status", "Notes"];
  const hRow = ws.addRow(headers);
  headers.forEach((_, i) => {
    const cell = hRow.getCell(i + 1);
    Object.assign(cell, { style: headerStyle() });
    cell.alignment = { ...cell.alignment, horizontal: i === 0 ? "left" : "center" };
  });
  hRow.height = 28;

  // Data validation for Status column (D)
  ws.dataValidations.add("D2:D200", {
    type: "list",
    allowBlank: true,
    formulae: ['"Not Started,In Progress,Complete,Blocked"'],
    showErrorMessage: true,
    errorTitle: "Invalid status",
    error: "Please select from the dropdown list.",
  });

  const tasks = [
    ["Review and post all accrual entries", "Controller", "", "Not Started", ""],
    ["Reconcile all bank accounts", "Staff Accountant", "", "Not Started", ""],
    ["Reconcile accounts payable subledger to GL", "AP Manager", "", "Not Started", ""],
    ["Reconcile accounts receivable subledger to GL", "AR Manager", "", "Not Started", ""],
    ["Reconcile prepaid expense accounts", "Staff Accountant", "", "Not Started", ""],
    ["Post depreciation and amortization entries", "Controller", "", "Not Started", ""],
    ["Reconcile fixed asset subledger to GL", "Staff Accountant", "", "Not Started", ""],
    ["Review and clear intercompany transactions", "Controller", "", "Not Started", ""],
    ["Post payroll journal entries", "Payroll Manager", "", "Not Started", ""],
    ["Reconcile payroll liabilities", "Payroll Manager", "", "Not Started", ""],
    ["Post deferred revenue adjustments", "Revenue Accountant", "", "Not Started", ""],
    ["Reconcile deferred revenue schedule to GL", "Revenue Accountant", "", "Not Started", ""],
    ["Review open purchase orders for accruals", "AP Manager", "", "Not Started", ""],
    ["Post inventory adjustments", "Inventory Accountant", "", "Not Started", ""],
    ["Reconcile inventory subledger to GL", "Inventory Accountant", "", "Not Started", ""],
    ["Prepare and review variance analysis", "FP&A Analyst", "", "Not Started", ""],
    ["Generate preliminary P&L and balance sheet", "Controller", "", "Not Started", ""],
    ["Review and obtain management sign-off", "CFO", "", "Not Started", ""],
    ["Lock accounting period in ERP", "Controller", "", "Not Started", ""],
    ["Distribute final financial package", "Controller", "", "Not Started", ""],
  ];

  tasks.forEach((task, i) => {
    const row = ws.addRow(task);
    row.height = 22;
    task.forEach((_, ci) => {
      const cell = row.getCell(ci + 1);
      const style = dataStyle(i, ci > 0 && ci !== 4);
      Object.assign(cell, { style });
    });
  });

  addBrandingFooter(ws, tasks.length + 1);
  return wb;
}

function buildBankReconciliation(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("Bank Reconciliation");
  setColWidths(ws, [38, 18, 18]);
  freezeHeader(ws);

  const addSection = (title: string, rowStart: number) => {
    const titleRow = ws.getRow(rowStart);
    const cell = titleRow.getCell(1);
    cell.value = title;
    cell.font = { bold: true, color: { argb: `FF${BRAND.accentFg}` }, size: 11 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND.accentBg}` } };
    ws.mergeCells(rowStart, 1, rowStart, 3);
    titleRow.height = 22;
  };

  // Title
  ws.mergeCells("A1:C1");
  const titleCell = ws.getCell("A1");
  titleCell.value = "Bank Reconciliation Template";
  Object.assign(titleCell, { style: headerStyle(true) });
  titleCell.font = { ...titleCell.font, size: 14 };
  ws.getRow(1).height = 32;

  // Meta
  ws.getCell("A2").value = "Company Name:";
  ws.getCell("B2").value = "";
  ws.getCell("A3").value = "Bank Account:";
  ws.getCell("B3").value = "";
  ws.getCell("A4").value = "Statement Date:";
  ws.getCell("B4").value = "";
  ws.getCell("A5").value = "Prepared By:";
  ws.getCell("B5").value = "";
  [2, 3, 4, 5].forEach((r) => {
    ws.getRow(r).getCell(1).font = { bold: true, size: 10 };
    ws.getRow(r).height = 18;
  });

  let r = 7;

  // GL Balance section
  addSection("BOOK (GL) BALANCE", r++);
  ws.getRow(r).values = ["Item", "Amount", "Notes"];
  ws.getRow(r).eachCell((c) => Object.assign(c, { style: headerStyle(false) }));
  ws.getRow(r++).height = 22;

  const glItems = [
    ["Balance per GL (beginning of month)", null, ""],
    ["Add: Deposits recorded in GL", null, ""],
    ["Less: Checks recorded in GL", null, ""],
    ["Add/Less: Other GL adjustments", null, ""],
  ];
  glItems.forEach((item, i) => {
    const row = ws.addRow(item);
    row.height = 20;
    row.getCell(1).style = dataStyle(i);
    row.getCell(2).style = currencyStyle(i);
    row.getCell(3).style = dataStyle(i);
    r++;
  });
  // GL Adjusted balance formula
  const glAdjRow = ws.addRow(["Adjusted GL Balance", { formula: `=B${r - 4}+B${r - 3}-B${r - 2}+B${r - 1}` }, ""]);
  glAdjRow.height = 22;
  glAdjRow.getCell(1).font = { bold: true, size: 10 };
  glAdjRow.getCell(2).style = { ...currencyStyle(0), font: { bold: true, size: 10 } };
  r++;

  r++; // blank row

  // Bank Statement section
  addSection("BANK STATEMENT BALANCE", r++);
  ws.getRow(r).values = ["Item", "Amount", "Notes"];
  ws.getRow(r).eachCell((c) => Object.assign(c, { style: headerStyle(false) }));
  ws.getRow(r++).height = 22;

  const bankItems = [
    ["Balance per Bank Statement", null, ""],
    ["Add: Deposits in Transit", null, ""],
    ["Less: Outstanding Checks", null, ""],
    ["Add/Less: Bank Errors", null, ""],
  ];
  const bankStart = r;
  bankItems.forEach((item, i) => {
    const row = ws.addRow(item);
    row.height = 20;
    row.getCell(1).style = dataStyle(i);
    row.getCell(2).style = currencyStyle(i);
    row.getCell(3).style = dataStyle(i);
    r++;
  });
  const bankAdjRow = ws.addRow(["Adjusted Bank Balance", { formula: `=B${bankStart}+B${bankStart + 1}-B${bankStart + 2}+B${bankStart + 3}` }, ""]);
  bankAdjRow.height = 22;
  bankAdjRow.getCell(1).font = { bold: true, size: 10 };
  bankAdjRow.getCell(2).style = { ...currencyStyle(0), font: { bold: true, size: 10 } };
  r++;

  r++;
  // Balance check
  const checkRow = ws.addRow(["DIFFERENCE (should be 0)", { formula: `=B${r - 2 - bankItems.length - 1}-B${r - 8 - glItems.length}` }, "✓ If 0, reconciliation is complete"]);
  checkRow.height = 24;
  checkRow.getCell(1).font = { bold: true, size: 11 };
  checkRow.getCell(2).numFmt = '"$"#,##0.00';
  checkRow.getCell(2).font = { bold: true, size: 11 };
  checkRow.getCell(3).font = { italic: true, color: { argb: `FF${BRAND.mutedText}` }, size: 10 };

  addBrandingFooter(ws, r + 2);
  return wb;
}

function buildExpenseReport(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("Expense Report");
  setColWidths(ws, [14, 34, 20, 14, 16, 14, 28]);
  freezeHeader(ws);

  // Title
  ws.mergeCells("A1:G1");
  const titleCell = ws.getCell("A1");
  titleCell.value = "EXPENSE REPORT";
  Object.assign(titleCell, { style: headerStyle(true) });
  titleCell.font = { ...titleCell.font, size: 14 };
  ws.getRow(1).height = 32;

  // Meta
  const metaRows = [
    ["Employee Name:", "", "Period Start:", ""],
    ["Department:", "", "Period End:", ""],
    ["Manager:", "", "Date Submitted:", ""],
  ];
  metaRows.forEach((mr, i) => {
    const row = ws.addRow(mr);
    row.height = 18;
    [1, 3].forEach((ci) => {
      row.getCell(ci).font = { bold: true, size: 10 };
    });
  });

  ws.addRow([]); // blank

  // Headers
  const headers = ["Date", "Description", "Category", "Amount", "Receipt?", "Billable?", "Notes"];
  const hRow = ws.addRow(headers);
  hRow.height = 26;
  headers.forEach((_, i) => {
    Object.assign(hRow.getCell(i + 1), { style: headerStyle() });
  });

  // Category validation
  ws.dataValidations.add("C7:C106", {
    type: "list",
    allowBlank: true,
    formulae: ['"Travel,Meals & Entertainment,Office Supplies,Software/Subscriptions,Training,Client Entertainment,Other"'],
  });
  // Receipt/Billable validation
  ws.dataValidations.add("E7:E106", { type: "list", allowBlank: true, formulae: ['"Yes,No"'] });
  ws.dataValidations.add("F7:F106", { type: "list", allowBlank: true, formulae: ['"Yes,No"'] });

  // Sample rows
  const sample = [
    ["", "Sample: Flight to client meeting", "Travel", 450.00, "Yes", "Yes", ""],
    ["", "Sample: Team lunch", "Meals & Entertainment", 85.50, "Yes", "No", ""],
    ["", "Sample: Office supplies", "Office Supplies", 32.99, "Yes", "No", ""],
  ];
  sample.forEach((row, i) => {
    const r = ws.addRow(row);
    r.height = 20;
    headers.forEach((_, ci) => {
      if (ci === 3) {
        r.getCell(ci + 1).style = currencyStyle(i);
        r.getCell(ci + 1).numFmt = '"$"#,##0.00';
      } else {
        r.getCell(ci + 1).style = dataStyle(i, ci > 0 && ci !== 6);
      }
    });
    r.getCell(1).numFmt = "mm/dd/yyyy";
  });

  // Add empty data rows
  for (let i = 3; i < 20; i++) {
    const r = ws.addRow(["", "", "", null, "", "", ""]);
    r.height = 20;
    headers.forEach((_, ci) => {
      if (ci === 3) r.getCell(ci + 1).style = currencyStyle(i);
      else r.getCell(ci + 1).style = dataStyle(i, ci > 0 && ci !== 6);
    });
    r.getCell(1).numFmt = "mm/dd/yyyy";
  }

  const totalRowNum = ws.rowCount + 1;
  // Total row
  const totalRow = ws.addRow(["", "TOTAL", "", { formula: `SUM(D7:D${totalRowNum - 1})` }, "", "", ""]);
  totalRow.height = 24;
  totalRow.getCell(2).font = { bold: true, size: 10 };
  totalRow.getCell(4).style = { ...currencyStyle(0), font: { bold: true, size: 11 } };
  totalRow.getCell(4).border = { top: { style: "medium" }, bottom: { style: "double" } };

  // Approval section
  ws.addRow([]);
  ws.addRow([]);
  const appRow = ws.addRow(["APPROVAL SECTION"]);
  appRow.getCell(1).font = { bold: true, size: 11, color: { argb: `FF${BRAND.accentFg}` } };
  ws.addRow(["Manager Name:", "", "Approval Date:", "", "Approved?", ""]);
  const approvedRow = ws.lastRow!;
  approvedRow.eachCell((c, ci) => { if (ci % 2 !== 0) c.font = { bold: true, size: 10 }; });
  ws.dataValidations.add(`F${approvedRow.number}:F${approvedRow.number}`, {
    type: "list", allowBlank: true, formulae: ['"Yes,No"'],
  });

  addBrandingFooter(ws, ws.rowCount + 1);
  return wb;
}

function buildIncomeStatement(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("Income Statement");
  setColWidths(ws, [38, 18, 18, 18]);
  freezeHeader(ws);

  ws.mergeCells("A1:D1");
  const titleCell = ws.getCell("A1");
  titleCell.value = "Income Statement";
  Object.assign(titleCell, { style: headerStyle(true) });
  titleCell.font = { ...titleCell.font, size: 14 };
  ws.getRow(1).height = 32;

  // Column headers
  const hRow = ws.addRow(["", "Current Period", "Prior Period", "Variance"]);
  hRow.height = 26;
  ["B", "C", "D"].forEach((col) => {
    const cell = ws.getCell(`${col}2`);
    cell.font = { bold: true, color: { argb: `FF${BRAND.headerFg}` }, size: 10 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND.headerBg}` } };
    cell.alignment = { horizontal: "center", vertical: "middle" };
  });

  const addSectionHeader = (label: string) => {
    const row = ws.addRow([label, "", "", ""]);
    row.height = 22;
    row.getCell(1).font = { bold: true, size: 10, color: { argb: `FF${BRAND.accentFg}` } };
    row.getCell(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND.accentBg}` } };
    ws.mergeCells(row.number, 1, row.number, 4);
    return row.number;
  };

  const addLineItem = (label: string, indent = false) => {
    const row = ws.addRow([indent ? `  ${label}` : label, null, null, null]);
    row.height = 18;
    row.getCell(1).font = { size: 10, color: { argb: `FF${BRAND.darkText}` } };
    ["B", "C"].forEach((col) => {
      const cell = ws.getCell(`${col}${row.number}`);
      cell.numFmt = '"$"#,##0.00';
      cell.alignment = { horizontal: "right" };
      cell.font = { size: 10 };
    });
    ws.getCell(`D${row.number}`).numFmt = '"$"#,##0.00';
    ws.getCell(`D${row.number}`).font = { size: 10 };
    ws.getCell(`D${row.number}`).alignment = { horizontal: "right" };
    return row.number;
  };

  const addSubtotal = (label: string, sumRange: string) => {
    const row = ws.addRow([label, { formula: `SUM(B${sumRange})` }, { formula: `SUM(C${sumRange})` }, { formula: `=B${ws.rowCount + 1}-C${ws.rowCount + 1}` }]);
    row.height = 22;
    row.getCell(1).font = { bold: true, size: 10 };
    ["B", "C", "D"].forEach((col) => {
      const cell = ws.getCell(`${col}${row.number}`);
      cell.numFmt = '"$"#,##0.00';
      cell.font = { bold: true, size: 10 };
      cell.border = { top: { style: "thin" }, bottom: { style: "medium" } };
      cell.alignment = { horizontal: "right" };
    });
    return row.number;
  };

  // Revenue
  addSectionHeader("REVENUE");
  const rev1 = addLineItem("Product Revenue", true);
  const rev2 = addLineItem("Service Revenue", true);
  const rev3 = addLineItem("Other Revenue", true);
  const grossRevRow = addSubtotal("Total Revenue", `${rev1}:${rev3}`);
  // Fix variance formula for subtotals
  ws.getCell(`D${grossRevRow}`).value = { formula: `=B${grossRevRow}-C${grossRevRow}` };

  ws.addRow([]); // blank

  // COGS
  addSectionHeader("COST OF GOODS SOLD");
  const cogs1 = addLineItem("Cost of Products Sold", true);
  const cogs2 = addLineItem("Cost of Services", true);
  const cogs3 = addLineItem("Other COGS", true);
  const cogsRow = addSubtotal("Total COGS", `${cogs1}:${cogs3}`);
  ws.getCell(`D${cogsRow}`).value = { formula: `=B${cogsRow}-C${cogsRow}` };

  ws.addRow([]);

  // Gross Profit
  const gpRow = ws.addRow(["GROSS PROFIT", { formula: `=B${grossRevRow}-B${cogsRow}` }, { formula: `=C${grossRevRow}-C${cogsRow}` }, { formula: `=B${ws.rowCount + 1}-C${ws.rowCount + 1}` }]);
  gpRow.height = 24;
  gpRow.getCell(1).font = { bold: true, size: 11 };
  ["B", "C", "D"].forEach((col) => {
    const cell = ws.getCell(`${col}${gpRow.number}`);
    cell.numFmt = '"$"#,##0.00';
    cell.font = { bold: true, size: 11 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND.accentBg}` } };
    cell.border = { top: { style: "medium" }, bottom: { style: "medium" } };
    cell.alignment = { horizontal: "right" };
  });
  ws.getCell(`D${gpRow.number}`).value = { formula: `=B${gpRow.number}-C${gpRow.number}` };

  ws.addRow([]);

  // Operating Expenses
  addSectionHeader("OPERATING EXPENSES");
  const oe1 = addLineItem("Salaries & Benefits", true);
  const oe2 = addLineItem("Rent & Occupancy", true);
  const oe3 = addLineItem("Marketing & Advertising", true);
  const oe4 = addLineItem("Technology & Software", true);
  const oe5 = addLineItem("Professional Services", true);
  const oe6 = addLineItem("Depreciation & Amortization", true);
  const oe7 = addLineItem("Other Operating Expenses", true);
  const opexRow = addSubtotal("Total Operating Expenses", `${oe1}:${oe7}`);
  ws.getCell(`D${opexRow}`).value = { formula: `=B${opexRow}-C${opexRow}` };

  ws.addRow([]);

  // Operating Income
  const oiRow = ws.addRow(["OPERATING INCOME", { formula: `=B${gpRow.number}-B${opexRow}` }, { formula: `=C${gpRow.number}-C${opexRow}` }, ""]);
  oiRow.height = 24;
  oiRow.getCell(1).font = { bold: true, size: 11 };
  ["B", "C"].forEach((col) => {
    const cell = ws.getCell(`${col}${oiRow.number}`);
    cell.numFmt = '"$"#,##0.00';
    cell.font = { bold: true, size: 11 };
    cell.border = { top: { style: "medium" }, bottom: { style: "medium" } };
    cell.alignment = { horizontal: "right" };
  });
  ws.getCell(`D${oiRow.number}`).value = { formula: `=B${oiRow.number}-C${oiRow.number}` };
  ws.getCell(`D${oiRow.number}`).numFmt = '"$"#,##0.00';
  ws.getCell(`D${oiRow.number}`).font = { bold: true, size: 11 };
  ws.getCell(`D${oiRow.number}`).alignment = { horizontal: "right" };

  ws.addRow([]);

  // Other Income/Expense
  addSectionHeader("OTHER INCOME / EXPENSE");
  const oth1 = addLineItem("Interest Income", true);
  const oth2 = addLineItem("Interest Expense", true);
  const oth3 = addLineItem("Other Income / Expense", true);

  ws.addRow([]);

  // Net Income
  const niRow = ws.addRow([
    "NET INCOME",
    { formula: `=B${oiRow.number}+B${oth1}+B${oth2}+B${oth3}` },
    { formula: `=C${oiRow.number}+C${oth1}+C${oth2}+C${oth3}` },
    "",
  ]);
  niRow.height = 28;
  niRow.getCell(1).font = { bold: true, size: 13, color: { argb: `FF${BRAND.accentFg}` } };
  ["B", "C"].forEach((col) => {
    const cell = ws.getCell(`${col}${niRow.number}`);
    cell.numFmt = '"$"#,##0.00';
    cell.font = { bold: true, size: 13, color: { argb: `FF${BRAND.accentFg}` } };
    cell.border = { top: { style: "double" }, bottom: { style: "double" } };
    cell.alignment = { horizontal: "right" };
  });
  ws.getCell(`D${niRow.number}`).value = { formula: `=B${niRow.number}-C${niRow.number}` };
  ws.getCell(`D${niRow.number}`).numFmt = '"$"#,##0.00';
  ws.getCell(`D${niRow.number}`).font = { bold: true, size: 13 };
  ws.getCell(`D${niRow.number}`).alignment = { horizontal: "right" };

  addBrandingFooter(ws, niRow.number + 3);
  return wb;
}

function buildBalanceSheet(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("Balance Sheet");
  setColWidths(ws, [38, 18, 18]);
  freezeHeader(ws);

  ws.mergeCells("A1:C1");
  const titleCell = ws.getCell("A1");
  titleCell.value = "Balance Sheet";
  Object.assign(titleCell, { style: headerStyle(true) });
  titleCell.font = { ...titleCell.font, size: 14 };
  ws.getRow(1).height = 32;

  const hRow = ws.addRow(["", "Current Period", "Prior Period"]);
  hRow.height = 26;
  ["B", "C"].forEach((col) => {
    const cell = ws.getCell(`${col}2`);
    cell.font = { bold: true, color: { argb: `FF${BRAND.headerFg}` }, size: 10 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND.headerBg}` } };
    cell.alignment = { horizontal: "center", vertical: "middle" };
  });

  const addSH = (label: string) => {
    const row = ws.addRow([label, "", ""]);
    row.height = 22;
    row.getCell(1).font = { bold: true, size: 10, color: { argb: `FF${BRAND.accentFg}` } };
    row.getCell(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${BRAND.accentBg}` } };
    ws.mergeCells(row.number, 1, row.number, 3);
    return row.number;
  };

  const addLI = (label: string, indent = false) => {
    const row = ws.addRow([indent ? `  ${label}` : label, null, null]);
    row.height = 18;
    ["B", "C"].forEach((col) => {
      const cell = ws.getCell(`${col}${row.number}`);
      cell.numFmt = '"$"#,##0.00';
      cell.alignment = { horizontal: "right" };
      cell.font = { size: 10 };
    });
    return row.number;
  };

  const addST = (label: string, startRow: number, endRow: number) => {
    const n = ws.rowCount + 1;
    const row = ws.addRow([label, { formula: `SUM(B${startRow}:B${endRow})` }, { formula: `SUM(C${startRow}:C${endRow})` }]);
    row.height = 22;
    row.getCell(1).font = { bold: true, size: 10 };
    ["B", "C"].forEach((col) => {
      const cell = ws.getCell(`${col}${n}`);
      cell.numFmt = '"$"#,##0.00';
      cell.font = { bold: true, size: 10 };
      cell.border = { top: { style: "thin" }, bottom: { style: "medium" } };
      cell.alignment = { horizontal: "right" };
    });
    return n;
  };

  // ASSETS
  addSH("ASSETS");
  addSH("Current Assets");
  const ca1 = addLI("Cash and Cash Equivalents", true);
  const ca2 = addLI("Accounts Receivable", true);
  const ca3 = addLI("Inventory", true);
  const ca4 = addLI("Prepaid Expenses", true);
  const ca5 = addLI("Other Current Assets", true);
  const totalCA = addST("Total Current Assets", ca1, ca5);

  ws.addRow([]);

  addSH("Non-Current Assets");
  const nca1 = addLI("Property, Plant & Equipment", true);
  const nca2 = addLI("Less: Accumulated Depreciation", true);
  const nca3 = addLI("Intangible Assets", true);
  const nca4 = addLI("Other Non-Current Assets", true);
  const totalNCA = addST("Total Non-Current Assets", nca1, nca4);

  ws.addRow([]);

  const totalAssetsRow = ws.rowCount + 1;
  const taRow = ws.addRow(["TOTAL ASSETS", { formula: `=B${totalCA}+B${totalNCA}` }, { formula: `=C${totalCA}+C${totalNCA}` }]);
  taRow.height = 28;
  taRow.getCell(1).font = { bold: true, size: 12 };
  ["B", "C"].forEach((col) => {
    const c = ws.getCell(`${col}${totalAssetsRow}`);
    c.numFmt = '"$"#,##0.00';
    c.font = { bold: true, size: 12, color: { argb: `FF${BRAND.accentFg}` } };
    c.border = { top: { style: "medium" }, bottom: { style: "double" } };
    c.alignment = { horizontal: "right" };
  });

  ws.addRow([]);
  ws.addRow([]);

  // LIABILITIES
  addSH("LIABILITIES & EQUITY");
  addSH("Current Liabilities");
  const cl1 = addLI("Accounts Payable", true);
  const cl2 = addLI("Accrued Liabilities", true);
  const cl3 = addLI("Short-term Debt", true);
  const cl4 = addLI("Deferred Revenue (current)", true);
  const cl5 = addLI("Other Current Liabilities", true);
  const totalCL = addST("Total Current Liabilities", cl1, cl5);

  ws.addRow([]);

  addSH("Non-Current Liabilities");
  const ltl1 = addLI("Long-term Debt", true);
  const ltl2 = addLI("Deferred Tax Liability", true);
  const ltl3 = addLI("Other Non-Current Liabilities", true);
  const totalLTL = addST("Total Non-Current Liabilities", ltl1, ltl3);

  ws.addRow([]);

  addSH("Equity");
  const eq1 = addLI("Common Stock", true);
  const eq2 = addLI("Additional Paid-in Capital", true);
  const eq3 = addLI("Retained Earnings", true);
  const eq4 = addLI("Other Equity", true);
  const totalEQ = addST("Total Equity", eq1, eq4);

  ws.addRow([]);

  const tlRow = ws.rowCount + 1;
  const tlRowObj = ws.addRow(["TOTAL LIABILITIES & EQUITY", { formula: `=B${totalCL}+B${totalLTL}+B${totalEQ}` }, { formula: `=C${totalCL}+C${totalLTL}+C${totalEQ}` }]);
  tlRowObj.height = 28;
  tlRowObj.getCell(1).font = { bold: true, size: 12 };
  ["B", "C"].forEach((col) => {
    const c = ws.getCell(`${col}${tlRow}`);
    c.numFmt = '"$"#,##0.00';
    c.font = { bold: true, size: 12, color: { argb: `FF${BRAND.accentFg}` } };
    c.border = { top: { style: "medium" }, bottom: { style: "double" } };
    c.alignment = { horizontal: "right" };
  });

  // Balance check
  ws.addRow([]);
  const bcRow = ws.addRow(["Balance Check (Assets - L&E, should be 0)", { formula: `=B${totalAssetsRow}-B${tlRow}` }, { formula: `=C${totalAssetsRow}-C${tlRow}` }]);
  bcRow.height = 22;
  bcRow.getCell(1).font = { italic: true, size: 10, color: { argb: `FF${BRAND.mutedText}` } };
  ["B", "C"].forEach((col) => {
    const c = ws.getCell(`${col}${bcRow.number}`);
    c.numFmt = '"$"#,##0.00';
    c.font = { size: 10, color: { argb: `FF${BRAND.mutedText}` } };
    c.alignment = { horizontal: "right" };
  });

  addBrandingFooter(ws, bcRow.number + 2);
  return wb;
}

function buildGeneralLedger(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("General Ledger");
  setColWidths(ws, [14, 12, 26, 34, 16, 14, 14, 16]);
  freezeHeader(ws);

  const headers = ["Date", "Account No.", "Account Name", "Description", "Reference", "Debit", "Credit", "Running Balance"];
  const hRow = ws.addRow(headers);
  hRow.height = 28;
  headers.forEach((_, i) => {
    const cell = hRow.getCell(i + 1);
    Object.assign(cell, { style: headerStyle() });
    cell.alignment = { ...cell.alignment, horizontal: i < 4 ? "left" : "center" };
  });

  // Sample rows
  const samples = [
    ["01/01/2025", "1000", "Cash", "Opening balance", "OB-001", 50000, null],
    ["01/05/2025", "1200", "Accounts Receivable", "Invoice #1001 - Acme Corp", "INV-1001", 12500, null],
    ["01/10/2025", "2000", "Accounts Payable", "Vendor payment - Office Depot", "CHK-0021", null, 2300],
    ["01/15/2025", "6100", "Salaries Expense", "Semi-monthly payroll", "PAY-01", null, 8500],
  ];

  samples.forEach((row, i) => {
    const r = ws.addRow([...row, null]); // Running Balance formula populated below
    r.height = 20;
    r.getCell(1).numFmt = "mm/dd/yyyy";
    r.getCell(1).style = { ...dataStyle(i), numFmt: "mm/dd/yyyy" };
    [2, 3, 4, 5].forEach((ci) => r.getCell(ci).style = dataStyle(i));
    [6, 7].forEach((ci) => {
      r.getCell(ci).style = currencyStyle(i);
      r.getCell(ci).numFmt = '"$"#,##0.00';
    });
    // Running balance
    const rowNum = r.number;
    r.getCell(8).value = i === 0
      ? { formula: `=F${rowNum}-G${rowNum}` }
      : { formula: `=H${rowNum - 1}+F${rowNum}-G${rowNum}` };
    r.getCell(8).style = currencyStyle(i);
    r.getCell(8).numFmt = '"$"#,##0.00';
  });

  // Empty rows
  for (let i = 4; i < 50; i++) {
    const rowNum = ws.rowCount + 1;
    const r = ws.addRow(["", "", "", "", "", null, null, null]);
    r.height = 20;
    [1, 2, 3, 4, 5].forEach((ci) => r.getCell(ci).style = dataStyle(i));
    [6, 7].forEach((ci) => { r.getCell(ci).style = currencyStyle(i); r.getCell(ci).numFmt = '"$"#,##0.00'; });
    r.getCell(8).value = { formula: `=IF(AND(F${rowNum}="",G${rowNum}=""),"",H${rowNum - 1}+IF(F${rowNum}="",0,F${rowNum})-IF(G${rowNum}="",0,G${rowNum}))` };
    r.getCell(8).style = currencyStyle(i);
    r.getCell(8).numFmt = '"$"#,##0.00';
    r.getCell(1).numFmt = "mm/dd/yyyy";
  }

  addBrandingFooter(ws, ws.rowCount + 2);
  return wb;
}

function buildTrialBalance(): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";
  const ws = wb.addWorksheet("Trial Balance");
  setColWidths(ws, [12, 34, 16, 16]);
  freezeHeader(ws);

  ws.mergeCells("A1:D1");
  const titleCell = ws.getCell("A1");
  titleCell.value = "Trial Balance";
  Object.assign(titleCell, { style: headerStyle(true) });
  titleCell.font = { ...titleCell.font, size: 14 };
  ws.getRow(1).height = 32;

  const meta = ws.addRow(["As of:", "", "", ""]);
  meta.height = 18;
  meta.getCell(1).font = { bold: true, size: 10 };

  const hRow = ws.addRow(["Account No.", "Account Name", "Debit", "Credit"]);
  hRow.height = 26;
  ["A", "B", "C", "D"].forEach((col) => {
    const cell = ws.getCell(`${col}3`);
    Object.assign(cell, { style: headerStyle() });
    cell.alignment = { ...cell.alignment, horizontal: col < "C" ? "left" : "right" };
  });

  const accounts = [
    ["1000", "Cash", 45000, null],
    ["1100", "Petty Cash", 500, null],
    ["1200", "Accounts Receivable", 32000, null],
    ["1300", "Inventory", 18000, null],
    ["1500", "Prepaid Expenses", 3600, null],
    ["1700", "Equipment", 120000, null],
    ["1800", "Accumulated Depreciation", null, 45000],
    ["2000", "Accounts Payable", null, 28000],
    ["2100", "Accrued Liabilities", null, 5000],
    ["2200", "Notes Payable", null, 50000],
    ["3000", "Common Stock", null, 100000],
    ["3100", "Retained Earnings", null, 12100],
    ["4000", "Revenue", null, 250000],
    ["5000", "Cost of Goods Sold", 150000, null],
    ["6100", "Salaries Expense", 85000, null],
    ["6200", "Rent Expense", 24000, null],
    ["6300", "Utilities Expense", 8000, null],
    ["6400", "Depreciation Expense", 4000, null],
  ];

  accounts.forEach((row, i) => {
    const r = ws.addRow(row);
    r.height = 18;
    r.getCell(1).style = dataStyle(i);
    r.getCell(2).style = dataStyle(i);
    r.getCell(3).style = currencyStyle(i);
    r.getCell(4).style = currencyStyle(i);
    [3, 4].forEach((ci) => r.getCell(ci).numFmt = '"$"#,##0.00');
  });

  // Blank rows
  for (let i = accounts.length; i < accounts.length + 15; i++) {
    const r = ws.addRow(["", "", null, null]);
    r.height = 18;
    [1, 2].forEach((ci) => r.getCell(ci).style = dataStyle(i));
    [3, 4].forEach((ci) => { r.getCell(ci).style = currencyStyle(i); r.getCell(ci).numFmt = '"$"#,##0.00'; });
  }

  const firstDataRow = 4;
  const lastDataRow = ws.rowCount;

  // Totals row
  const totals = ws.addRow([
    "",
    "TOTALS",
    { formula: `SUM(C${firstDataRow}:C${lastDataRow})` },
    { formula: `SUM(D${firstDataRow}:D${lastDataRow})` },
  ]);
  totals.height = 26;
  totals.getCell(2).font = { bold: true, size: 11 };
  [3, 4].forEach((ci) => {
    totals.getCell(ci).numFmt = '"$"#,##0.00';
    totals.getCell(ci).font = { bold: true, size: 11 };
    totals.getCell(ci).border = { top: { style: "medium" }, bottom: { style: "double" } };
    totals.getCell(ci).alignment = { horizontal: "right" };
  });

  // Balance check
  ws.addRow([]);
  const check = ws.addRow(["", "Balance Check (Debits - Credits):", { formula: `=C${totals.number}-D${totals.number}` }, ""]);
  check.height = 22;
  check.getCell(2).font = { bold: true, size: 10 };
  check.getCell(3).numFmt = '"$"#,##0.00';
  check.getCell(3).font = { bold: true, size: 10 };
  check.getCell(3).alignment = { horizontal: "right" };

  addBrandingFooter(ws, ws.rowCount + 2);
  return wb;
}

// ── Generic fallback generator ─────────────────────────────────────────────
interface Template {
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  steps: Array<{ title: string; description: string }>;
  benefits: string[];
}

function buildGenericWorkbook(template: Template): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Vergo";

  // Sheet 1: Info
  const infoWs = wb.addWorksheet("Overview");
  infoWs.getColumn(1).width = 24;
  infoWs.getColumn(2).width = 60;

  infoWs.mergeCells("A1:B1");
  const titleCell = infoWs.getCell("A1");
  titleCell.value = template.title;
  Object.assign(titleCell, { style: headerStyle(true) });
  titleCell.font = { ...titleCell.font, size: 14 };
  infoWs.getRow(1).height = 32;

  infoWs.addRow([]);
  const descRow = infoWs.addRow(["Description", template.description]);
  descRow.height = 40;
  descRow.getCell(1).font = { bold: true, size: 10 };
  descRow.getCell(2).alignment = { wrapText: true, vertical: "top" };
  descRow.getCell(2).font = { size: 10 };

  infoWs.addRow(["Category", template.category]);
  infoWs.lastRow!.getCell(1).font = { bold: true, size: 10 };

  infoWs.addRow([]);
  const brandRow = infoWs.addRow(["Source", "Vergo — tryvergo.com"]);
  brandRow.getCell(1).font = { bold: true, size: 10 };
  brandRow.getCell(2).font = { size: 10, color: { argb: `FF${BRAND.accentFg}` } };

  // Sheet 2: Steps
  const stepsWs = wb.addWorksheet("How to Use");
  stepsWs.getColumn(1).width = 8;
  stepsWs.getColumn(2).width = 28;
  stepsWs.getColumn(3).width = 60;
  freezeHeader(stepsWs);

  const stepsHeader = stepsWs.addRow(["Step", "Title", "Description"]);
  stepsHeader.height = 26;
  ["A", "B", "C"].forEach((col) => {
    Object.assign(stepsWs.getCell(`${col}1`), { style: headerStyle() });
  });

  template.steps.forEach((step, i) => {
    const r = stepsWs.addRow([i + 1, step.title, step.description]);
    r.height = 40;
    r.getCell(1).style = { ...dataStyle(i, true) };
    r.getCell(2).style = { ...dataStyle(i), font: { bold: true, size: 10 } };
    r.getCell(3).style = { ...dataStyle(i), alignment: { wrapText: true, vertical: "top" } };
  });

  // Sheet 3: Checklist
  const checkWs = wb.addWorksheet("Checklist");
  checkWs.getColumn(1).width = 42;
  checkWs.getColumn(2).width = 22;
  checkWs.getColumn(3).width = 14;
  checkWs.getColumn(4).width = 18;
  checkWs.getColumn(5).width = 30;
  freezeHeader(checkWs);

  const chHeaders = ["Task", "Owner", "Due Date", "Status", "Notes"];
  const chRow = checkWs.addRow(chHeaders);
  chRow.height = 26;
  chHeaders.forEach((_, i) => Object.assign(chRow.getCell(i + 1), { style: headerStyle() }));

  checkWs.dataValidations.add("D2:D100", {
    type: "list",
    allowBlank: true,
    formulae: ['"Not Started,In Progress,Complete,Blocked"'],
  });

  template.steps.forEach((step, i) => {
    const r = checkWs.addRow([step.title, "", "", "Not Started", ""]);
    r.height = 20;
    chHeaders.forEach((_, ci) => r.getCell(ci + 1).style = dataStyle(i, ci > 0 && ci !== 4));
  });

  return wb;
}

// ── Generator map ──────────────────────────────────────────────────────────
const customGenerators: Record<string, () => ExcelJS.Workbook> = {
  "standard-month-end-close-checklist": buildMonthEndCloseChecklist,
  "close-timeline-checklist": buildMonthEndCloseChecklist,
  "month-end-close-checklist": buildMonthEndCloseChecklist,
  "financial-close-checklist": buildMonthEndCloseChecklist,
  "monthly-accounting-checklist": buildMonthEndCloseChecklist,
  "accounting-workflow-template": buildMonthEndCloseChecklist,
  "bank-reconciliation": buildBankReconciliation,
  "bank-account-reconciliation": buildBankReconciliation,
  "cash-reconciliation-template": buildBankReconciliation,
  "expense-report-template": buildExpenseReport,
  "income-statement-template": buildIncomeStatement,
  "balance-sheet-template": buildBalanceSheet,
  "balance-sheet-reconciliation": buildBalanceSheet,
  "general-ledger-template": buildGeneralLedger,
  "trial-balance-template": buildTrialBalance,
};

// ── Main ───────────────────────────────────────────────────────────────────
console.log(`\n🚀 Vergo Excel Template Generator`);
console.log(`📁 Output: ${OUTPUT_DIR}\n`);

const generated: string[] = [];
const failed: Array<{ slug: string; error: string }> = [];

for (const template of templates) {
  try {
    const wb = customGenerators[template.slug]
      ? customGenerators[template.slug]()
      : buildGenericWorkbook(template);

    wb.created = new Date();
    wb.modified = new Date();

    const outPath = join(OUTPUT_DIR, `${template.slug}.xlsx`);
    await wb.xlsx.writeFile(outPath);
    generated.push(template.slug);
    process.stdout.write(`  ✓ ${template.slug}\n`);
  } catch (err) {
    failed.push({ slug: template.slug, error: String(err) });
    process.stdout.write(`  ✗ ${template.slug}: ${err}\n`);
  }
}

console.log(`\n✅ Generated: ${generated.length} templates`);
if (failed.length > 0) {
  console.log(`❌ Failed: ${failed.length}`);
  failed.forEach((f) => console.log(`   - ${f.slug}: ${f.error}`));
}

// Update downloadableTemplates.ts
const slugList = generated.map((s) => `  "${s}",`).join("\n");
const newContent = `// Slugs that have a corresponding Excel file in /public/downloads/[slug].xlsx
// Updated automatically by scripts/generate-templates.mts after running npm run generate-templates
export const downloadableTemplates = new Set<string>([
${slugList}
]);
`;
writeFileSync(join(ROOT, "src", "data", "downloadableTemplates.ts"), newContent, "utf-8");
console.log(`\n📝 Updated src/data/downloadableTemplates.ts with ${generated.length} slugs`);
